<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PokeTokenBar.Tray</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PokeTokenBar.Core\PokeTokenBar.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.21" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.21" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.21" />
  </ItemGroup>

</Project>
