<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PokeTokenBar.Core\PokeTokenBar.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StreamJsonRpc" Version="2.25.29" />
  </ItemGroup>

</Project>
